name: 'coreason_etl_icd10'
version: '1.0.0'
config-version: 2

profile: 'coreason_etl_icd10'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

on-run-start:
  - 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'

clean-targets:
  - "target"
  - "dbt_packages"

models:
  coreason_etl_icd10:
    silver:
      +materialized: table
    gold:
      +materialized: view
