name: "coreason_etl_icd_10"
version: "1.0.0"
config-version: 2

profile: "coreason_etl_icd_10"

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'

models:
  coreason_etl_icd_10:
    +materialized: table
