name: "coreason_etl_icd_10"
version: "1.0.0"
config-version: 2

profile: "coreason_etl_icd_10"

model-paths: ["models"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  coreason_etl_icd_10:
    +materialized: table
