version: 2

models:
  - name: coreason_etl_icd_10_silver_icd10_ontology
    description: "Silver layer clean table standardizing ICD-10 codes."
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - formatted_icd10_code
            - fiscal_year
    columns:
      - name: coreason_id
        description: "UUID5 Identity Resolution based on the ICD10 Namespace and formatted code."
        tests:
          - unique
          - not_null
      - name: formatted_icd10_code
        description: "Standardized code with proper decimal placement."
        tests:
          - not_null
      - name: fiscal_year
        description: "The CMS fiscal year."
        tests:
          - not_null
      - name: ingestion_ts
        description: "Timestamp of ingestion."
        tests:
          - not_null
      - name: long_description
        description: "The long-form clinical description of the code."
        tests:
          - not_null
